<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JS error ) try catch finally , if throw error</title>
</head>

<body>

    <p>Please input a number between 5 and 10:</p>

    <input id="demo" type="text" value="0">
    <button type="button" onclick="myFunction()">Test Input</button>
    <p id="p01"></p>

    <script>
        function myFunction() {
            const message = document.getElementById("p01");
            message.innerHTML = "";
            let x = document.getElementById("demo").value;
            try {
                // throw "err" -> err은 catch절에 들어가는 err 
                if (x == "") throw "empty";
                if (isNaN(x)) throw "not a Number";
                x = Number(x);
                if (x < 5) throw "too low";
                if (x > 10) throw "too high";
            } catch (err) {
                message.innerHTML = "Input is " + err;
            } 
            
            // 초기화
            finally {
                document.getElementById("demo").value = "";
            }
        }
    </script>

</body>

</html>